server:
  port: 9411

spring:
  application:
    name: "zipkin-distributed-tracing-server"
  main:
    allow-bean-definition-overriding: true

management:
  metrics:
    web:
      server:
        auto-time-requests: false