server:
    port: 5555

spring:
    application:
        name: zuul-server

zuul:
    ignored-services: "*"
    prefix: "/api"
    routes:
        organization-service: "/organization/**"
        licensing-service: "/licensing/**"

eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka/

hystrix:
    command:
        default.execution.isolation.thread.timeoutInMilliseconds: 2500
        license-service.execution.isolation.thread.timeoutInMilliseconds: 7000


management:
    endpoints:
        web:
            exposure:
                include:
                    - "info"
                    - "health"
                    - "routes"