server:
    port: 5555

spring:
    application:
        name: zuul-server
    cloud:
        config:
            uri: http://localhost:8888
zuul:
    ignored-services: "*"
    prefix: "/api"
    routes:
        organization-service: "/organization/**"
        licensing-service: "/licensing/**"

eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka/

management:
    endpoints:
        web:
            exposure:
                include:
                    - "info"
                    - "health"
                    - "routes"
                    - "refresh"