spring:
  application:
    name: "service-consumer"

server:
  port: 8100


#microservice-a:
#  ribbon:
#    listOfServers: http://localhost:8080,http://localhost:8081

  zipkin:
    base-url: "http://localhost:9411"
    sender:
      type: rabbit
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1